[2022-12-06 11:17:31,358] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_mongo_db_dag.LoadPositionsInMongoDB 2022-12-05T00:00:00+00:00 [queued]>
[2022-12-06 11:17:31,380] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_mongo_db_dag.LoadPositionsInMongoDB 2022-12-05T00:00:00+00:00 [queued]>
[2022-12-06 11:17:31,380] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 11:17:31,380] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-12-06 11:17:31,380] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 11:17:31,390] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): LoadPositionsInMongoDB> on 2022-12-05T00:00:00+00:00
[2022-12-06 11:17:31,395] {standard_task_runner.py:52} INFO - Started process 208 to run task
[2022-12-06 11:17:31,399] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_mongo_db_dag', 'LoadPositionsInMongoDB', '2022-12-05T00:00:00+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_mongo_db_dag.py', '--cfg-path', '/tmp/tmpe5w45bgn', '--error-file', '/tmp/tmpwxz4i3fv']
[2022-12-06 11:17:31,400] {standard_task_runner.py:77} INFO - Job 5: Subtask LoadPositionsInMongoDB
[2022-12-06 11:17:31,454] {logging_mixin.py:104} INFO - Running <TaskInstance: my_mongo_db_dag.LoadPositionsInMongoDB 2022-12-05T00:00:00+00:00 [running]> on host 90b7908d868d
[2022-12-06 11:17:31,538] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_mongo_db_dag
AIRFLOW_CTX_TASK_ID=LoadPositionsInMongoDB
AIRFLOW_CTX_EXECUTION_DATE=2022-12-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-05T00:00:00+00:00
[2022-12-06 11:17:31,938] {logging_mixin.py:104} INFO - debut de chargement des données dans mongodb
[2022-12-06 11:17:31,938] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_mongo_db_dag.py", line 55, in load
    l.load(cl, dict_positions)
  File "/opt/airflow/scripts/mongo/load_aircraft_position_data_in_mongodb.py", line 28, in load
    mycol.insert_many(dict_positions)
  File "/home/airflow/.local/lib/python3.6/site-packages/pymongo/collection.py", line 690, in insert_many
    blk.ops = [doc for doc in gen()]
  File "/home/airflow/.local/lib/python3.6/site-packages/pymongo/collection.py", line 690, in <listcomp>
    blk.ops = [doc for doc in gen()]
  File "/home/airflow/.local/lib/python3.6/site-packages/pymongo/collection.py", line 681, in gen
    common.validate_is_document_type("document", document)
  File "/home/airflow/.local/lib/python3.6/site-packages/pymongo/common.py", line 516, in validate_is_document_type
    "collections.MutableMapping" % (option,)
TypeError: document must be an instance of dict, bson.son.SON, bson.raw_bson.RawBSONDocument, or a type that inherits from collections.MutableMapping
[2022-12-06 11:17:31,942] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=my_mongo_db_dag, task_id=LoadPositionsInMongoDB, execution_date=20221205T000000, start_date=20221206T111731, end_date=20221206T111731
[2022-12-06 11:17:32,012] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-12-06 11:55:54,706] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_mongo_db_dag.LoadPositionsInMongoDB 2022-12-05T00:00:00+00:00 [queued]>
[2022-12-06 11:55:54,728] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_mongo_db_dag.LoadPositionsInMongoDB 2022-12-05T00:00:00+00:00 [queued]>
[2022-12-06 11:55:54,728] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 11:55:54,729] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-12-06 11:55:54,729] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 11:55:54,741] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): LoadPositionsInMongoDB> on 2022-12-05T00:00:00+00:00
[2022-12-06 11:55:54,746] {standard_task_runner.py:52} INFO - Started process 284 to run task
[2022-12-06 11:55:54,750] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_mongo_db_dag', 'LoadPositionsInMongoDB', '2022-12-05T00:00:00+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_mongo_db_dag.py', '--cfg-path', '/tmp/tmpsvspl0xe', '--error-file', '/tmp/tmp2peovbqm']
[2022-12-06 11:55:54,751] {standard_task_runner.py:77} INFO - Job 9: Subtask LoadPositionsInMongoDB
[2022-12-06 11:55:54,794] {logging_mixin.py:104} INFO - Running <TaskInstance: my_mongo_db_dag.LoadPositionsInMongoDB 2022-12-05T00:00:00+00:00 [running]> on host d4b3d166a83f
[2022-12-06 11:55:54,835] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_mongo_db_dag
AIRFLOW_CTX_TASK_ID=LoadPositionsInMongoDB
AIRFLOW_CTX_EXECUTION_DATE=2022-12-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-05T00:00:00+00:00
[2022-12-06 11:55:54,996] {logging_mixin.py:104} INFO - debut de chargement des données dans mongodb
[2022-12-06 11:55:55,284] {logging_mixin.py:104} INFO - fin de chargement des données dans mongodb
[2022-12-06 11:55:55,287] {python.py:151} INFO - Done. Returned value was: None
[2022-12-06 11:55:55,298] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_mongo_db_dag, task_id=LoadPositionsInMongoDB, execution_date=20221205T000000, start_date=20221206T115554, end_date=20221206T115555
[2022-12-06 11:55:55,328] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-06 11:55:55,353] {local_task_job.py:151} INFO - Task exited with return code 0
