[2022-12-06 10:00:38,176] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_elastic_search_dag.LoadFlightsInES 2022-12-06T10:00:32.958539+00:00 [queued]>
[2022-12-06 10:00:38,186] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_elastic_search_dag.LoadFlightsInES 2022-12-06T10:00:32.958539+00:00 [queued]>
[2022-12-06 10:00:38,187] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 10:00:38,187] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-12-06 10:00:38,187] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 10:00:38,200] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): LoadFlightsInES> on 2022-12-06T10:00:32.958539+00:00
[2022-12-06 10:00:38,204] {standard_task_runner.py:52} INFO - Started process 340 to run task
[2022-12-06 10:00:38,208] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_elastic_search_dag', 'LoadFlightsInES', '2022-12-06T10:00:32.958539+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_elastic_search_dag.py', '--cfg-path', '/tmp/tmp8cmzxmgn', '--error-file', '/tmp/tmp0gs11cl0']
[2022-12-06 10:00:38,209] {standard_task_runner.py:77} INFO - Job 7: Subtask LoadFlightsInES
[2022-12-06 10:00:38,261] {logging_mixin.py:104} INFO - Running <TaskInstance: my_elastic_search_dag.LoadFlightsInES 2022-12-06T10:00:32.958539+00:00 [running]> on host 3d95da7470fe
[2022-12-06 10:00:38,392] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_elastic_search_dag
AIRFLOW_CTX_TASK_ID=LoadFlightsInES
AIRFLOW_CTX_EXECUTION_DATE=2022-12-06T10:00:32.958539+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-06T10:00:32.958539+00:00
[2022-12-06 10:00:38,422] {base.py:150} WARNING - PUT http://elastic-search:9200/flights [status:400 request:0.006s]
[2022-12-06 10:00:38,422] {logging_mixin.py:104} INFO - L'index flights existe déjà
[2022-12-06 10:00:38,422] {logging_mixin.py:104} INFO - debut de chargement des données dans elasticsearch
[2022-12-06 10:00:38,422] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_elastic_search_dag.py", line 55, in load
    l.load(es, dict_flights)
  File "/opt/airflow/scripts/load_flight_data_in_elasticsearch.py", line 123, in load
    for doc in dict['flight']:
TypeError: list indices must be integers or slices, not str
[2022-12-06 10:00:38,425] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=my_elastic_search_dag, task_id=LoadFlightsInES, execution_date=20221206T100032, start_date=20221206T100038, end_date=20221206T100038
[2022-12-06 10:00:38,463] {local_task_job.py:151} INFO - Task exited with return code 1
