[2022-12-06 09:18:32,057] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_elastic_search_dag.CheckElasticSearchConnexion 2022-12-06T09:18:18.787588+00:00 [queued]>
[2022-12-06 09:18:32,073] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_elastic_search_dag.CheckElasticSearchConnexion 2022-12-06T09:18:18.787588+00:00 [queued]>
[2022-12-06 09:18:32,074] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 09:18:32,074] {taskinstance.py:1088} INFO - Starting attempt 3 of 51
[2022-12-06 09:18:32,074] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 09:18:32,083] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): CheckElasticSearchConnexion> on 2022-12-06T09:18:18.787588+00:00
[2022-12-06 09:18:32,087] {standard_task_runner.py:52} INFO - Started process 1187 to run task
[2022-12-06 09:18:32,092] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_elastic_search_dag', 'CheckElasticSearchConnexion', '2022-12-06T09:18:18.787588+00:00', '--job-id', '29', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_elastic_search_dag.py', '--cfg-path', '/tmp/tmp_v2f9_0a', '--error-file', '/tmp/tmpg_dxkyku']
[2022-12-06 09:18:32,093] {standard_task_runner.py:77} INFO - Job 29: Subtask CheckElasticSearchConnexion
[2022-12-06 09:18:32,145] {logging_mixin.py:104} INFO - Running <TaskInstance: my_elastic_search_dag.CheckElasticSearchConnexion 2022-12-06T09:18:18.787588+00:00 [running]> on host 27e998575b9f
[2022-12-06 09:18:32,206] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_elastic_search_dag
AIRFLOW_CTX_TASK_ID=CheckElasticSearchConnexion
AIRFLOW_CTX_EXECUTION_DATE=2022-12-06T09:18:18.787588+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-06T09:18:18.787588+00:00
[2022-12-06 09:18:32,207] {logging_mixin.py:104} INFO - 47
[2022-12-06 09:18:32,207] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_elastic_search_dag.py", line 29, in random_fail_task
    raise Exception('This task randomly failed')
Exception: This task randomly failed
[2022-12-06 09:18:32,210] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=my_elastic_search_dag, task_id=CheckElasticSearchConnexion, execution_date=20221206T091818, start_date=20221206T091832, end_date=20221206T091832
[2022-12-06 09:18:32,268] {local_task_job.py:151} INFO - Task exited with return code 1
