[2022-12-06 09:00:30,940] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_elastic_search_dag.CheckElasticSearchConnexion manual__2022-12-06T08:59:53.859099+00:00 [queued]>
[2022-12-06 09:00:30,955] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_elastic_search_dag.CheckElasticSearchConnexion manual__2022-12-06T08:59:53.859099+00:00 [queued]>
[2022-12-06 09:00:30,955] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 09:00:30,955] {taskinstance.py:1377} INFO - Starting attempt 5 of 51
[2022-12-06 09:00:30,955] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 09:00:30,975] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): CheckElasticSearchConnexion> on 2022-12-06 08:59:53.859099+00:00
[2022-12-06 09:00:30,983] {standard_task_runner.py:52} INFO - Started process 225 to run task
[2022-12-06 09:00:30,988] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_elastic_search_dag', 'CheckElasticSearchConnexion', 'manual__2022-12-06T08:59:53.859099+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/my_elastic_search_dag.py', '--cfg-path', '/tmp/tmpm4zmtjlo', '--error-file', '/tmp/tmp_4sp9ii7']
[2022-12-06 09:00:30,989] {standard_task_runner.py:80} INFO - Job 11: Subtask CheckElasticSearchConnexion
[2022-12-06 09:00:31,083] {task_command.py:371} INFO - Running <TaskInstance: my_elastic_search_dag.CheckElasticSearchConnexion manual__2022-12-06T08:59:53.859099+00:00 [running]> on host 94e1b8231027
[2022-12-06 09:00:31,226] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_elastic_search_dag
AIRFLOW_CTX_TASK_ID=CheckElasticSearchConnexion
AIRFLOW_CTX_EXECUTION_DATE=2022-12-06T08:59:53.859099+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-06T08:59:53.859099+00:00
[2022-12-06 09:00:31,228] {logging_mixin.py:115} INFO - 32
[2022-12-06 09:00:31,228] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_elastic_search_dag.py", line 29, in random_fail_task
    raise Exception('This task randomly failed')
Exception: This task randomly failed
[2022-12-06 09:00:31,240] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=my_elastic_search_dag, task_id=CheckElasticSearchConnexion, execution_date=20221206T085953, start_date=20221206T090030, end_date=20221206T090031
[2022-12-06 09:00:31,257] {standard_task_runner.py:97} ERROR - Failed to execute job 11 for task CheckElasticSearchConnexion (This task randomly failed; 225)
[2022-12-06 09:00:31,280] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-06 09:00:31,333] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
