[2022-12-06 09:11:52,822] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_elastic_search_dag.CheckElasticSearchConnexion 2022-12-06T09:11:33.393301+00:00 [queued]>
[2022-12-06 09:11:52,835] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_elastic_search_dag.CheckElasticSearchConnexion 2022-12-06T09:11:33.393301+00:00 [queued]>
[2022-12-06 09:11:52,836] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 09:11:52,836] {taskinstance.py:1088} INFO - Starting attempt 4 of 51
[2022-12-06 09:11:52,836] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 09:11:52,842] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): CheckElasticSearchConnexion> on 2022-12-06T09:11:33.393301+00:00
[2022-12-06 09:11:52,846] {standard_task_runner.py:52} INFO - Started process 612 to run task
[2022-12-06 09:11:52,849] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_elastic_search_dag', 'CheckElasticSearchConnexion', '2022-12-06T09:11:33.393301+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_elastic_search_dag.py', '--cfg-path', '/tmp/tmp3vi7erfp', '--error-file', '/tmp/tmppc23ios2']
[2022-12-06 09:11:52,849] {standard_task_runner.py:77} INFO - Job 9: Subtask CheckElasticSearchConnexion
[2022-12-06 09:11:52,962] {logging_mixin.py:104} INFO - Running <TaskInstance: my_elastic_search_dag.CheckElasticSearchConnexion 2022-12-06T09:11:33.393301+00:00 [running]> on host 27e998575b9f
[2022-12-06 09:11:53,006] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_elastic_search_dag
AIRFLOW_CTX_TASK_ID=CheckElasticSearchConnexion
AIRFLOW_CTX_EXECUTION_DATE=2022-12-06T09:11:33.393301+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-06T09:11:33.393301+00:00
[2022-12-06 09:11:53,007] {logging_mixin.py:104} INFO - 43
[2022-12-06 09:11:53,007] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_elastic_search_dag.py", line 29, in random_fail_task
    raise Exception('This task randomly failed')
Exception: This task randomly failed
[2022-12-06 09:11:53,008] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=my_elastic_search_dag, task_id=CheckElasticSearchConnexion, execution_date=20221206T091133, start_date=20221206T091152, end_date=20221206T091153
[2022-12-06 09:11:53,063] {local_task_job.py:151} INFO - Task exited with return code 1
