[2022-12-06 08:59:52,403] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_elastic_search_dag.CheckElasticSearchConnexion scheduled__2022-12-05T00:00:00+00:00 [queued]>
[2022-12-06 08:59:52,417] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_elastic_search_dag.CheckElasticSearchConnexion scheduled__2022-12-05T00:00:00+00:00 [queued]>
[2022-12-06 08:59:52,417] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 08:59:52,417] {taskinstance.py:1377} INFO - Starting attempt 1 of 51
[2022-12-06 08:59:52,417] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 08:59:52,433] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): CheckElasticSearchConnexion> on 2022-12-05 00:00:00+00:00
[2022-12-06 08:59:52,439] {standard_task_runner.py:52} INFO - Started process 172 to run task
[2022-12-06 08:59:52,443] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_elastic_search_dag', 'CheckElasticSearchConnexion', 'scheduled__2022-12-05T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/my_elastic_search_dag.py', '--cfg-path', '/tmp/tmpvtpcwnhk', '--error-file', '/tmp/tmpy6bg5uom']
[2022-12-06 08:59:52,445] {standard_task_runner.py:80} INFO - Job 2: Subtask CheckElasticSearchConnexion
[2022-12-06 08:59:52,460] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-12-06 08:59:52,521] {task_command.py:371} INFO - Running <TaskInstance: my_elastic_search_dag.CheckElasticSearchConnexion scheduled__2022-12-05T00:00:00+00:00 [running]> on host 94e1b8231027
[2022-12-06 08:59:52,607] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_elastic_search_dag
AIRFLOW_CTX_TASK_ID=CheckElasticSearchConnexion
AIRFLOW_CTX_EXECUTION_DATE=2022-12-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-05T00:00:00+00:00
[2022-12-06 08:59:52,608] {logging_mixin.py:115} INFO - 60
[2022-12-06 08:59:52,609] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_elastic_search_dag.py", line 29, in random_fail_task
    raise Exception('This task randomly failed')
Exception: This task randomly failed
[2022-12-06 08:59:52,619] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=my_elastic_search_dag, task_id=CheckElasticSearchConnexion, execution_date=20221205T000000, start_date=20221206T085952, end_date=20221206T085952
[2022-12-06 08:59:52,631] {standard_task_runner.py:97} ERROR - Failed to execute job 2 for task CheckElasticSearchConnexion (This task randomly failed; 172)
[2022-12-06 08:59:52,655] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-06 08:59:52,803] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
